# Generated by Django 5.0.6 on 2024-05-22 20:26

import core.services.upload_car_img
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^(?!.*\\s)[A-Z][a-z]{1,49}(?<!\\s)$', ['First letter of brand must be only uppercase letters.', 'Not aloud spaces at the beginning or end of the brand.', 'Second letter of brand must be only lowercase letters.', 'Length of brand must be between 3 and 50 characters.'])]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.services.upload_car_img.upload_car_img, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
